version: '3.8'

services:
  db:
    image: mongo
    volumes:
      - db_data:/index
    ports:
      - 27017:27017
    networks:
      - backend
  app:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db_data: